import { mkdir } from "node:fs/promises";
import { z } from "zod";
import { Placemark } from "./types";

const listedBuildingSchema = z.object({
  geometry: z.string(),
  name: z.string(),
  reference: z.string(),
  documentation_url: z.string().url().optional(),
  listed_building_grade: z.string().optional(),
  latitude: z.number(),
  longitude: z.number(),
});

const PLACEMARK_ID = "placemark-green";

const geoJsonPlacemarks = (geojson: unknown): Placemark[] =>
  z
    .array(listedBuildingSchema)
    .parse(geojson)
    .map((feature) => ({
      name: feature.name,
      description: `Grade ${feature.listed_building_grade} listed building. ${feature.documentation_url}`,
      styleUrl: `#${PLACEMARK_ID}`,
      Point: {
        coordinates: `${feature.longitude},${feature.latitude}`,
      },
    }));

const frontMatter = `<?xml version="1.0" encoding="UTF-8"?>
<kml
	xmlns="http://earth.google.com/kml/2.2">
	<Document>
		<Style id="${PLACEMARK_ID}">
			<IconStyle>
				<Icon>
					<href>https://omaps.app/placemarks/${PLACEMARK_ID}.png</href>
				</Icon>
			</IconStyle>
		</Style>
		<name>Listed buildings</name>
		<visibility>1</visibility>
    `;

const endMatter = `	</Document>
</kml>`;

const placemarkToKml = (placemark: Placemark) => {
  return `
  <Placemark>
    <name>${placemark.name}</name>
    <description>${placemark.description}
    
    <!DOCTYPE html><html prefix="dc: http://purl.org/dc/terms/ mw: http://mediawiki.org/rdf/" about="https://en.wikipedia.org/wiki/Special:Redirect/revision/1198949434" class="no-editing"><head prefix="mwr: https://en.wikipedia.org/wiki/Special:Redirect/"><meta charset="utf-8"><meta property="mw:pageId" content="11435907"><meta property="mw:pageNamespace" content="0"><meta property="mw:revisionSHA1" content="cb261a0f68b0697d0d667c048a6fde9f8eceabdd"><meta property="dc:modified" content="2024-01-25T13:28:49.000Z"><meta property="mw:htmlVersion" content="2.8.0"><meta property="mw:html:version" content="2.8.0"><link rel="dc:isVersionOf" href="//en.wikipedia.org/wiki/Frederick_Bremer"><base href="//en.wikipedia.org/wiki/"><title>Frederick Bremer</title><meta property="mw:generalModules" content="ext.cite.ux-enhancements|mediawiki.page.media"><meta property="mw:moduleStyles" content="ext.cite.parsoid.styles|ext.cite.styles"><meta http-equiv="content-language" content="en"><meta http-equiv="vary" content="Accept"><link rel="stylesheet" href="//meta.wikimedia.org/api/rest_v1/data/css/mobile/base"><link rel="stylesheet" href="//en.wikipedia.org/api/rest_v1/data/css/mobile/site"><link rel="stylesheet" href="//meta.wikimedia.org/api/rest_v1/data/css/mobile/pcs"><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, shrink-to-fit=no"><script src="//meta.wikimedia.org/api/rest_v1/data/javascript/mobile/pcs"></script><link rel="icon" href="data:,"><meta property="pcs:locale" content="en"><meta property="mw:leadImage" content="https://upload.wikimedia.org/wikipedia/commons/4/4f/Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg" data-file-width="2587" data-file-height="2070"></head><body lang="en" class="mw-content-ltr sitedir-ltr ltr mw-body-content parsoid-body mediawiki mw-parser-output content skin-minerva" dir="ltr" data-mw-parsoid-version="0.20.0.0-alpha16" data-mw-html-version="2.8.0"><div id="pcs" class="mw-parser-output"><script>pcs.c1.Page.onBodyStart();</script><header><div class="pcs-edit-section-header v2"><div class="pcs-header-inner-left"><h1 data-id="0" class="pcs-edit-section-title"><span class="mw-page-title-main">Frederick Bremer</span></h1><p data-description-source="local" data-wikdata-entity-id="Q5497411" id="pcs-edit-section-title-description">British engineer and inventor</p><hr id="pcs-edit-section-divider"></div><div class="pcs-header-inner-right"></div></div></header><section data-mw-section-id="0"><span class="pcs-edit-section-link-container"><a href="/w/index.php?title=Frederick_Bremer&amp;action=edit&amp;section=0" data-id="0" data-action="edit_section" aria-labelledby="pcs-edit-section-aria-normal" class="pcs-edit-section-link"></a></span><p><b>Frederick William Bremer</b> (12 July 1872 in <a href="./Stepney" title="Stepney">Stepney</a>, London – 1941 in <a href="./Walthamstow" title="Walthamstow">Walthamstow</a>, England) was a British <a href="./Gasfitter" title="Gasfitter" class="mw-redirect">gasfitter</a>, <a href="./Plumber" title="Plumber">plumber</a>, <a href="./Engineer" title="Engineer">engineer</a> and <a href="./Inventor" title="Inventor" class="mw-redirect">inventor</a> recognised as the man who built the first petrol-fuelled car in Great Britain in 1892.</p>

<meta property="mw:PageProp/toc" data-mw="{&quot;autoGenerated&quot;:true}">
<style data-mw-deduplicate="TemplateStyles:r1236091366" typeof="mw:Extension/templatestyles mw:Transclusion">.mw-parser-output .ambox{border:1px solid #a2a9b1;border-left:10px solid #36c;background-color:#fbfbfb;box-sizing:border-box}.mw-parser-output .ambox+link+.ambox,.mw-parser-output .ambox+link+style+.ambox,.mw-parser-output .ambox+link+link+.ambox,.mw-parser-output .ambox+.mw-empty-elt+link+.ambox,.mw-parser-output .ambox+.mw-empty-elt+link+style+.ambox,.mw-parser-output .ambox+.mw-empty-elt+link+link+.ambox{margin-top:-1px}html body.mediawiki .mw-parser-output .ambox.mbox-small-left{margin:4px 1em 4px 0;overflow:hidden;width:238px;border-collapse:collapse;font-size:88%;line-height:1.25em}.mw-parser-output .ambox-speedy{border-left:10px solid #b32424;background-color:#fee7e6}.mw-parser-output .ambox-delete{border-left:10px solid #b32424}.mw-parser-output .ambox-content{border-left:10px solid #f28500}.mw-parser-output .ambox-style{border-left:10px solid #fc3}.mw-parser-output .ambox-move{border-left:10px solid #9932cc}.mw-parser-output .ambox-protection{border-left:10px solid #a2a9b1}.mw-parser-output .ambox .mbox-text{border:none;padding:0.25em 0.5em;width:100%}.mw-parser-output .ambox .mbox-image{border:none;padding:2px 0 2px 0.5em;text-align:center}.mw-parser-output .ambox .mbox-imageright{border:none;padding:2px 0.5em 2px 0;text-align:center}.mw-parser-output .ambox .mbox-empty-cell{border:none;padding:0;width:1px}.mw-parser-output .ambox .mbox-image-div{width:52px}html.client-js body.skin-minerva .mw-parser-output .mbox-text-span{margin-left:23px!important}@media(min-width:720px){.mw-parser-output .ambox{margin:0 10%}}@media print{body.ns-0 .mw-parser-output .ambox{display:none!important}}</style><table class="box-More_footnotes_needed plainlinks metadata ambox ambox-style ambox-More_footnotes_needed" role="presentation"><tbody><tr><td class="mbox-image"><div class="mbox-image-div"><span><span><img alt="" resource="./File:Text_document_with_red_question_mark.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Text_document_with_red_question_mark.svg/40px-Text_document_with_red_question_mark.svg.png" decoding="async" data-file-width="48" data-file-height="48" data-file-type="drawing" height="40" width="40" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Text_document_with_red_question_mark.svg/60px-Text_document_with_red_question_mark.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Text_document_with_red_question_mark.svg/80px-Text_document_with_red_question_mark.svg.png 2x" class="mw-file-element pcs-no-lazy-load"></span></span></div></td><td class="mbox-text"><div class="mbox-text-span">This article includes a list of general <a href="./Wikipedia:Citing_sources" title="Wikipedia:Citing sources">references</a>, but <b>it lacks sufficient corresponding <a href="./Wikipedia:Citing_sources#Inline_citations" title="Wikipedia:Citing sources">inline citations</a></b>.  <span class="date-container"><i>(<span class="date">August 2017</span>)</i></span></div></td></tr></tbody></table>
<p class="mw-empty-elt"><span></span>
<span></span></p>
<style data-mw-deduplicate="TemplateStyles:r1237879389" typeof="mw:Extension/templatestyles mw:Transclusion">.mw-parser-output .infobox-subbox{padding:0;border:none;margin:-3px;width:auto;min-width:100%;font-size:100%;clear:none;float:none;background-color:transparent}.mw-parser-output .infobox-3cols-child{margin:auto}.mw-parser-output .infobox .navbar{font-size:100%}body.skin-minerva .mw-parser-output .infobox-header,body.skin-minerva .mw-parser-output .infobox-subheader,body.skin-minerva .mw-parser-output .infobox-above,body.skin-minerva .mw-parser-output .infobox-title,body.skin-minerva .mw-parser-output .infobox-image,body.skin-minerva .mw-parser-output .infobox-full-data,body.skin-minerva .mw-parser-output .infobox-below{text-align:center}@media screen{html.skin-theme-clientpref-night .mw-parser-output .infobox-full-data:not(.notheme)>div:not(.notheme)[style]{background:#1f1f23!important;color:#f8f9fa}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .infobox-full-data:not(.notheme) div:not(.notheme){background:#1f1f23!important;color:#f8f9fa}}@media(min-width:640px){body.skin--responsive .mw-parser-output .infobox-table{display:table!important}body.skin--responsive .mw-parser-output .infobox-table>caption{display:table-caption!important}body.skin--responsive .mw-parser-output .infobox-table>tbody{display:table-row-group}body.skin--responsive .mw-parser-output .infobox-table tr{display:table-row!important}body.skin--responsive .mw-parser-output .infobox-table th,body.skin--responsive .mw-parser-output .infobox-table td{padding-left:inherit;padding-right:inherit}}</style><div class="pcs-collapse-table-container"><div class="pcs-collapse-table-collapsed-container pcs-collapse-table-expanded" style="display: block;"><strong class="pcs-table-infobox">Quick Facts</strong><span class="pcs-collapse-table-collapse-text"> Born, Died ...</span><span class="pcs-collapse-table-aria" aria-labelledby="pcs-collapse-table-aria-expand" role="button" display="none"><span id="pcs-collapse-table-aria-expand" aria-label="Expand table"></span><span id="pcs-collapse-table-aria-collapse" aria-label="Collapse table"></span></span></div><div class="pcs-collapse-table-content" style="display: none;"><table class="infobox biography vcard pcs-collapse-table"><tbody><tr><th colspan="2" class="infobox-above"><div class="fn">Frederick William Bremer</div></th></tr><tr><th scope="row" class="infobox-label">Born</th><td class="infobox-data"><span style="display:none">(<span class="bday">1872-07-12</span>)</span>12 July 1872<br><div style="display:inline" class="birthplace"><a href="./Stepney" title="Stepney">Stepney</a>, <a href="./Middlesex" title="Middlesex">Middlesex</a>, England</div></td></tr><tr><th scope="row" class="infobox-label">Died</th><td class="infobox-data">1941<br><div style="display:inline" class="deathplace"><a href="./Walthamstow" title="Walthamstow">Walthamstow</a>, <a href="./Essex" title="Essex">Essex</a>, England</div></td></tr><tr><th scope="row" class="infobox-label">Occupation</th><td class="infobox-data role">Engineer</td></tr><tr><td colspan="2" class="infobox-full-data"><b>Engineering career</b></td></tr><tr><th scope="row" class="infobox-label">Practice name</th><td class="infobox-data org">Frederick Bremer Motor Manufacturer<br>Bremer Engineering Company, Motor Manufacturers</td></tr><tr class="note"><th scope="row" class="infobox-label">Projects</th><td class="infobox-data">The Bremer Car, the first British four-wheeled motor car with an internal combustion engine</td></tr><tr><th scope="row" class="infobox-label">Significant advance</th><td class="infobox-data">Zelish, Nyron, Andre</td></tr><tr style="display:none"><td colspan="2">
</td></tr></tbody></table></div><div class="pcs-collapse-table-collapsed-bottom pcs-collapse-table-icon" style="display: none;">Close</div></div>
<figure class="mw-default-size mw-halign-right pcs-widen-image-ancestor" typeof="mw:File/Thumb"><a href="./File:Bremer_car_at_Vestry_House_Museum,_Walthamstow.jpg" class="mw-file-description pcs-widen-image-ancestor"><img resource="./File:Bremer_car_at_Vestry_House_Museum,_Walthamstow.jpg" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg/640px-Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg" decoding="async" data-file-width="2587" data-file-height="2070" data-file-type="bitmap" height="512" width="640" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg/960px-Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg/1280px-Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg 2x" class="mw-file-element pcs-no-lazy-load pcs-widen-image-override" data-file-original-src="//upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg/220px-Bremer_car_at_Vestry_House_Museum%2C_Walthamstow.jpg"></a><figcaption>The Bremer car on display at <a href="./Vestry_House_Museum" title="Vestry House Museum">Vestry House Museum</a>, Walthamstow</figcaption></figure>

</section><section data-mw-section-id="1" style="display: none;"><div class="pcs-edit-section-header v2"><h2 id="Bremer_car" class="pcs-edit-section-title">Bremer car</h2><span class="pcs-edit-section-link-container"><a href="/w/index.php?title=Frederick_Bremer&amp;action=edit&amp;section=1" data-id="1" data-action="edit_section" aria-labelledby="pcs-edit-section-aria-normal" class="pcs-edit-section-link"></a></span></div>
<p>A gas-fitter and plumber by trade, Frederick is remembered for building (with assistant Tom Bates) the first British four-wheeled motor car with an internal combustion engine in 1892 (claimed in 1912 by the British magazine <i>Motor</i>). In 1894 he took his car on the roads of <a href="./Walthamstow" title="Walthamstow">Walthamstow</a>, his home town.</p>

<p>After completing the car Bremer moved on to other projects including a four-cylinder car in 1894 which has not survived to the present day. Bremer also operated a series of small businesses, including the Bremer Engineering Company, and took out patents, which included one for improved gears for motor carriages.<sup class="mw-ref reference left-touch-area" id="cite_ref-1"><a href="./Frederick_Bremer#cite_note-1" style="counter-reset: mw-Ref 1;" class="reference-link"><span class="mw-reflink-text">[1]</span></a></sup><sup class="noprint Inline-Template Template-Fact" style="white-space:nowrap;"><span>[</span><i><a href="./Wikipedia:Citation_needed" title="Wikipedia:Citation needed"><span>citation needed</span></a></i><span>]</span></sup></p>

<p>Frederick married Annie Elizabeth Garner on 22 April 1916, despite the marriage certificate listing him as Frederick Brewer, and his father as Gerberd Brewer.</p>

<p>In 1933 Bremer donated his car to the <a href="./Vestry_House_Museum" title="Vestry House Museum">Vestry House Museum</a> in Walthamstow, where it can still be seen. In 1964 the Bremer Car was entered into the <a href="./London_to_Brighton_Veteran_Car_Run" title="London to Brighton Veteran Car Run">London to Brighton Veteran Car Run</a> enlisted as car number 1, but the crankshaft broke after <span>17 miles (27</span><span>&nbsp;</span><span>km)</span>. The next year, again as car number 1, it completed the <span>54-mile (87</span><span>&nbsp;</span><span>km)</span> course in just under eight hours.</p>

<p>Bremer died in 1941 and is buried at St Mary's Church in Walthamstow along with his wife Annie.</p>

</section><section data-mw-section-id="2" style="display: none;"><div class="pcs-edit-section-header v2"><h2 id="Legacy" class="pcs-edit-section-title">Legacy</h2><span class="pcs-edit-section-link-container"><a href="/w/index.php?title=Frederick_Bremer&amp;action=edit&amp;section=2" data-id="2" data-action="edit_section" aria-labelledby="pcs-edit-section-aria-normal" class="pcs-edit-section-link"></a></span></div>
<p><a href="./Frederick_Bremer_School" title="Frederick Bremer School">Frederick Bremer School</a>, a specialist engineering college named after Bremer, opened in September 2008. The school replaced <a href="./Warwick_School_for_Boys" title="Warwick School for Boys">Warwick School for Boys</a> and <a href="./Aveling_Park_School" title="Aveling Park School">Aveling Park School</a>.</p>

</section><section data-mw-section-id="3" style="display: none;"><div class="pcs-edit-section-header v2"><h2 id="See_also" class="pcs-edit-section-title">See also</h2><span class="pcs-edit-section-link-container"><a href="/w/index.php?title=Frederick_Bremer&amp;action=edit&amp;section=3" data-id="3" data-action="edit_section" aria-labelledby="pcs-edit-section-aria-normal" class="pcs-edit-section-link"></a></span></div>
<ul><li><a href="./John_Henry_Knight_(inventor)" title="John Henry Knight (inventor)">John Henry Knight</a></li></ul>

</section><hr class="pcs-fold-hr"><section data-mw-section-id="4" style="display: none;"><div class="pcs-edit-section-header v2 pcs-section-hideable-header" onclick="pcs.c1.Sections.setHidden('4', false);"><span id="pcs-section-control-4" class="pcs-section-control pcs-section-control-show" role="button" aria-labelledby="pcs-section-aria-expand"></span><h2 id="References" class="pcs-edit-section-title">References</h2><span class="pcs-edit-section-link-container"><a href="/w/index.php?title=Frederick_Bremer&amp;action=edit&amp;section=4" data-id="4" data-action="edit_section" aria-labelledby="pcs-edit-section-aria-normal" class="pcs-edit-section-link"></a></span></div>




<div id="pcs-section-content-4" class="pcs-section-hidden"><style data-mw-deduplicate="TemplateStyles:r1239543626" typeof="mw:Extension/templatestyles mw:Transclusion">.mw-parser-output .reflist{margin-bottom:0.5em;list-style-type:decimal}@media screen{.mw-parser-output .reflist{font-size:90%}}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}</style><div class="reflist   " about="#mwt22">
<div class="mw-references-wrap" about="#mwt26"><ol class="mw-references references"><li id="cite_note-1"><div class="pcs-ref"><div class="pcs-ref-backlink-container"><a id="back_link_cite_note-1" class="pcs-ref-back-link" href="./Frederick_Bremer#pcs-ref-back-link-cite_note-1" pcs-back-links="[&quot;./Frederick_Bremer#cite_ref-1&quot;]">[1]</a></div><div class="pcs-ref-body"><span id="mw-reference-text-cite_note-1" class="mw-reference-text reference-text"><style data-mw-deduplicate="TemplateStyles:r1238218222" typeof="mw:Extension/templatestyles mw:Transclusion">.mw-parser-output cite.citation{font-style:inherit;word-wrap:break-word}.mw-parser-output .citation q{quotes:"\"""\"""'""'"}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}.mw-parser-output .id-lock-free.id-lock-free a{background:url("//upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-limited.id-lock-limited a,.mw-parser-output .id-lock-registration.id-lock-registration a{background:url("//upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-subscription.id-lock-subscription a{background:url("//upload.wikimedia.org/wikipedia/commons/a/aa/Lock-red-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .cs1-ws-icon a{background:url("//upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg")right 0.1em center/12px no-repeat}body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-free a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-limited a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-registration a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-subscription a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .cs1-ws-icon a{background-size:contain;padding:0 1em 0 0}.mw-parser-output .cs1-code{color:inherit;background:inherit;border:none;padding:inherit}.mw-parser-output .cs1-hidden-error{display:none;color:var(--color-error,#d33)}.mw-parser-output .cs1-visible-error{color:var(--color-error,#d33)}.mw-parser-output .cs1-maint{display:none;color:#085;margin-left:0.3em}.mw-parser-output .cs1-kern-left{padding-left:0.2em}.mw-parser-output .cs1-kern-right{padding-right:0.2em}.mw-parser-output .citation .mw-selflink{font-weight:inherit}@media screen{.mw-parser-output .cs1-format{font-size:95%}html.skin-theme-clientpref-night .mw-parser-output .cs1-maint{color:#18911f}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .cs1-maint{color:#18911f}}</style><cite class="citation web cs1"><a rel="mw:ExtLink nofollow" href="http://gaukmotors.co.uk/motorpedia/car-make/bremer" class="external text">"Bremer Motorpedia ALL models, history and specifications"</a>.</cite></span></div></div></li></ol></div></div><style data-mw-deduplicate="TemplateStyles:r1239549316" typeof="mw:Extension/templatestyles mw:Transclusion">.mw-parser-output .refbegin{margin-bottom:0.5em}.mw-parser-output .refbegin-hanging-indents>ul{margin-left:0}.mw-parser-output .refbegin-hanging-indents>ul>li{margin-left:0;padding-left:3.2em;text-indent:-3.2em}.mw-parser-output .refbegin-hanging-indents ul,.mw-parser-output .refbegin-hanging-indents ul li{list-style:none}@media(max-width:720px){.mw-parser-output .refbegin-hanging-indents>ul>li{padding-left:1.6em;text-indent:-1.6em}}.mw-parser-output .refbegin-columns{margin-top:0.3em}.mw-parser-output .refbegin-columns ul{margin-top:0}.mw-parser-output .refbegin-columns li{page-break-inside:avoid;break-inside:avoid-column}@media screen{.mw-parser-output .refbegin{font-size:90%}}</style><div class="refbegin  
    " style="" about="#mwt27">
<ul><li><cite id="CITEREFNigel_Sadler.1999" class="citation book cs1">Nigel Sadler. (1999). <i>The Story of the Bremer Car</i>. Vestry House Museum. <a href="./ISBN_(identifier)" title="ISBN (identifier)" class="mw-redirect">ISBN</a><span>&nbsp;</span><a href="./Special:BookSources/0-901974-43-9" title="Special:BookSources/0-901974-43-9"><bdi>0-901974-43-9</bdi></a>.</cite></li></ul>
</div></div></section><section data-mw-section-id="5" style="display: none;"><div class="pcs-edit-section-header v2 pcs-section-hideable-header" onclick="pcs.c1.Sections.setHidden('5', false);"><span id="pcs-section-control-5" class="pcs-section-control pcs-section-control-show" role="button" aria-labelledby="pcs-section-aria-expand"><span id="pcs-section-aria-expand" aria-label="Expand section"></span><span id="pcs-section-aria-collapse" aria-label="Collapse section"></span></span><h2 id="External_links" class="pcs-edit-section-title">External links</h2><span class="pcs-edit-section-link-container"><span id="pcs-edit-section-aria-normal" aria-label="Edit section"></span><span id="pcs-edit-section-aria-protected" aria-label="Edit section on protected page"></span><a href="/w/index.php?title=Frederick_Bremer&amp;action=edit&amp;section=5" data-id="5" data-action="edit_section" aria-labelledby="pcs-edit-section-aria-normal" class="pcs-edit-section-link"></a></span></div>










<div id="pcs-section-content-5" class="pcs-section-hidden"><ul><li><a rel="mw:ExtLink nofollow" href="http://www.bremer.org.uk/" class="external text">Frederick Bremer School Home Page</a></li></ul><span></span></div></section><script defer="true">pcs.c1.Page.onBodyEnd();</script></div></body></html>
    </description>
    <styleUrl>${placemark.styleUrl}</styleUrl>
    <Point>
      <coordinates>${placemark.Point.coordinates}</coordinates>
    </Point>
  </Placemark>
  `;
};

const convertPlacemarksToKml = (placemarks: Placemark[]) => {
  return placemarks.map(placemarkToKml).join("\n");
};

const allPlacemarksText = (placemarks: Placemark[]) =>
  `${frontMatter}${convertPlacemarksToKml(placemarks)}${endMatter}`;

export const generateListedBuildingsKml = async () => {
  const foo = await Bun.file(
    "largeFiles/filtered-listed-buildings.geojson"
  ).text();
  const allPlacemarks = geoJsonPlacemarks(JSON.parse(foo));

  // make a new output folder and then create a new file for each in batches of 2000
  const outputFolder = "largeFiles/listed-buildings-output";
  await mkdir(outputFolder);
  const batchSize = 10000;
  for (let i = 0; i < allPlacemarks.length; i += batchSize) {
    const batch = allPlacemarks.slice(i, i + batchSize);
    // replace all & with because otherwise did not parse well
    const file = allPlacemarksText(batch).replace(/&/g, "and");
    Bun.write(
      `${outputFolder}/listed-buildings-${Math.floor((i + 1) / batchSize)}.kml`,
      file
    );
  }

  const file = allPlacemarksText(geoJsonPlacemarks(JSON.parse(foo))).replace(
    /&/g,
    "and"
  );

  Bun.write("largeFiles/blue-plaques-output.kml", file);
};
